version: "3"
services:

  mongodb:
    image: mongo:4-bionic
    ports:
      - 28017:27017
    volumes:
      - ../mongodata:/data/db
  
  ccb_dev:
    build: .
    command: npm run dev
    restart: on-failure
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb
